apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-python-client
  labels:
    app: mssql-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-python-app
  template:
    metadata:
      labels:
        app: mssql-python-app
    spec:
      containers:
      - name: mssql-python-container
        image: rluiarch/custom-mssql-tools:1.0.1  # Replace this with your image name
        env:
        - name: MSSQL_endpoint
          value: "mssql-server"  # Kubernetes service name for MSSQL
        - name: MSSQL_port
          value: "1433"
        - name: MSSQL_user
          value: "SA"
        - name: MSSQL_password
          value: "password123"
        - name: SA_PASSWORD
          value: "password123"
        command: ["/bin/bash"]  # Run bash instead of the Python script, sine py script not tested yet
        args: ["-c", "while true; do sleep 3600; done"]  # Keep the pod alive with an infinite loop
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          requests:
            memory: "1024Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-server
spec:
  selector:
    app: mssql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
