apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-python-client
  labels:
    app: mssql-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-python-app
  template:
    metadata:
      labels:
        app: mssql-python-app
    spec:
      restartPolicy: Always
      containers:
      - name: mssql-python-container
        image: rluiarch/custom-mssql-tools:latest  # Replace this with your image name
        env:
        - name: MSSQL_endpoint
          value: "mssql-server"  # Kubernetes service name for MSSQL
        - name: MSSQL_port
          value: "1433"
        - name: MSSQL_user
          value: "SA"
        - name: MSSQL_password
          value: "password123"
        - name: SA_PASSWORD
          value: "password123"
        command: ["/bin/bash", "-c", "/usr/bin/python3 /app/sqlloadquery.py"]
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          requests:
            memory: "1024Mi"
            cpu: "500m"
        # Optionally, you can add a livenessProbe and readinessProbe
        # Uncomment if needed to ensure the pod is always "alive" and "ready"
        # livenessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/healthy
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        # readinessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/ready
        #   initialDelaySeconds: 30
        #   periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-server
spec:
  selector:
    app: mssql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
